config/routes.rb
Bookmark::Application.routes.draw do

 resources :users

  root to: 'users#index'
  match '/about', to:'static_pages#about'
  match '/contact', to:'static_pages#contact'
 match '/home', to:'static_pages#home'
  match '/signup', to:'users#new'

end

app/models/new_bookmark.rb
class NewBookmark < ActiveRecord::Base
  attr_accessible :address, :name, :tags
  validates :name, presence: true
  validates_format_of :address, :with=>URI::regexp(%w(http https))
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :address, :name, :tags
  validates :name, presence: true
  validates_format_of :address, :with=>URI::regexp(%w(http https))
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def show
    @bookmark=NewBookmark.find(params[:id])
  end

  def new
    @bookmark=NewBookmark.new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
   # if @user.save
      # Handle a successful save.
      #redirect_to @user
    #  redirect_to users_url
    #else
     # render 'new'
    #end
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.js   {}
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
    @user = User.new
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def update
     @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
    #  sign_in @user
     # redirect_to @user
      redirect_to users_url
    else
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/new.html.erb
<% provide(:title, 'New Bookmark') %>
<h1>New Bookmark</h1>



<%= form_for(@bookmark) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
<% end %>

app/views/bookmarks/show.html.erb
<%= @bookmark.name %>, <%= @bookmark.address %>,<%= @bookmark.tags %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmark | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Bookmarks", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    home_path %></li>
          <li><%= link_to "About",   about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
<h1>Bookmarks</h1>
<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  bookmark application.
</p>
  <%= link_to "New Bookmark", signup_path, class: "btn btn-large btn-primary" %>
</div>

app/views/users/_user.html.erb
<li>

  <%= link_to user.name, user %>
    <%=user.address%>
      <%=user.tags%>
        <%= link_to "Edit", edit_user_path(user), class: "btn btn-large btn-primary" %>
          <%= link_to "delete", user, method: :delete,
          data: { confirm: "You sure?" }, class: "btn btn-large btn-primary" %>
</li>

app/views/users/create.js.erb
$("<%= escape_javascript(render @user) %>").appendTo("#users");

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>Update bookmark</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_field :address%>

      <%= f.label :tags %>
      <%= f.text_field :tags%>


      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>


  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All Bookmarks</h1>

<%#= button_to "Create", :action => "new", :remote => true, :form => { "data-type" => "json" } %>
<!--
<ul class="users">
  <#% @users.each do |user| %>
    <li>

      <#%= link_to user.name, user %>
      <#%=user.address%>
      <#%=user.tags%>
      <#%= link_to "Edit", edit_user_path(user), class: "btn btn-large btn-primary" %>
      <#%= link_to "delete", user, method: :delete,
                  data: { confirm: "You sure?" }, class: "btn btn-large btn-primary" %>
    </li>
  <#% end %>
</ul>
-->

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user, remote: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :tags %>
      <%= f.text_field :tags %>


      <%= f.submit class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
<br>
<%= link_to "New Bookmark", signup_path, class: "btn btn-large btn-primary",retmote:true %>
<ul id="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'New Bookmark') %>
<h1>New Bookmark</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :tags %>
      <%= f.text_field :tags %>


      <%= f.submit "Create Bookmark", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<p><%= @user.name %>, <%= @user.address %></p>
<%= link_to "Edit", edit_user_path(User.find(params[:id])), class: "btn btn-large btn-primary" %>
<%#= link_to "Delete", user, method: :delete,data: { confirm: "You sure?" }, class: "btn btn-large btn-primary" %>